[package]
name = "tipb"
version = "0.0.1"
edition = "2018"

[features]
gen = []

[lib]
name = "tipb"

[dependencies]
protobuf = "~2.0"

[build-dependencies]
protobuf-build = { path = "../grpc-rs/protobuf-build" }
