[package]
name = "tipb"
version = "0.0.1"
edition = "2018"

[features]
gen = []

[lib]
name = "tipb"

[dependencies]
prost = { version = "0.5" }
prost-derive = { version = "0.5" }
bytes = { version = "0.4" }
lazy_static = { version = "1.3" }

[build-dependencies]
protobuf-build = "0.6"
